# Generated by Django 3.2 on 2023-04-25 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Здесь нужно ввести название категории.', max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Здесь нужно задать слаг категории.', unique=True, verbose_name='Слаг категории')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Здесь нужно ввести название жанра.', max_length=100, verbose_name='Название жанра')),
                ('slug', models.SlugField(help_text='Здесь нужно задать слаг жанра.', unique=True, verbose_name='Слаг жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Здесь нужно ввести название произведения.', max_length=200, verbose_name='Название произведения')),
                ('year', models.IntegerField(help_text='Здесь нужно ввести год выхода.', verbose_name='Год выхода')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(blank=True, help_text='Здесь нужно выбрать категорию.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.category', verbose_name='Категория')),
                ('genre', models.ManyToManyField(blank=True, help_text='Здесь нужно выбрать жанр.', null=True, related_name='titles', to='reviews.Genre', verbose_name='Жанр')),
            ],
        ),
    ]
